docker_repo               = "ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_focal"
img_tag                   = "ubuntu_focal"
docker_base_img           = "ubuntu:focal"
vagrant_base_img          = "ubuntu/focal64"
extra_packages            = ""
workspace_ansible_version = "2.9"
