docker_repo               = "ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_focal"
img_tag                   = "ubuntu_focal"
container_base_img        = "src-base-ubuntu_focal:latest"
vagrant_base_img          = "ubuntu/focal64"
extra_packages            = ""
workspace_ansible_version = "9.1.0"
