img_name                  = "src-test-workspace"
docker_repo               = "ghcr.io/utrechtuniversity/src-test-workspace"
img_tag                   = "ubuntu_focal-desktop"
docker_base_img           = "ubuntu:focal"
vagrant_base_img          = "ubuntu/focal64"
extra_packages            = "xfce4"
workspace_ansible_version = "2.9"
