img_name                  = "src-ubuntu_focal_desktop"
docker_base_img           = "ubuntu:focal"
vagrant_base_img          = "ubuntu/focal64"
extra_packages            = "xfce4"
workspace_ansible_version = "2.9"
