container_repo            = "ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_noble"
img_tag                   = "ubuntu_noble"
container_base_img        = "src-base-ubuntu_noble:latest"
vagrant_base_img          = "ubuntu/noble64"
extra_packages            = ""
workspace_ansible_version = "9.1.0"
