docker_repo               = "ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_jammy"
img_tag                   = "ubuntu_jammy"
docker_base_img           = "ubuntu:jammy"
vagrant_base_img          = "ubuntu/jammy64"
extra_packages            = ""
workspace_ansible_version = "2.9"
