docker_repo               = "ghcr.io/utrechtuniversity/src-test-workspace:ubuntu_jammy"
img_tag                   = "ubuntu_jammy"
container_base_img        = "src-base-ubuntu_jammy:latest"
vagrant_base_img          = "ubuntu/jammy64"
extra_packages            = ""
workspace_ansible_version = "9.0.0"
