FROM docker.io/ubuntu:noble
RUN apt update -y && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends systemd sudo util-linux-extra zlib1g-dev
RUN ln -s /lib/systemd/systemd /sbin/init
